### ISSUE TITLE
One of THE best themes I've ever used. hands down. 😍 😍 😍  🔥 🔥 🔥 

### ISSUE THREAD

**Issue by jamischarles** [ghifarit53/tokyonight-vim#18]
Just wanted to say this is one of THE best themes I've ever used. hands down. 😍 😍 😍 

Not just the color choices, but choosing what tokens have more vs less contrast have quickly made it my preferred theme.

yml, JS, and JSON code look really really great.

If I ever make my own theme I'll fork this because it has such great structure.
🔥 🔥 🔥

**Comment by ghifarit53** [comment]
Thank you @jamischarles!

All credits of the theme goes to @ enkia, the original author of the colorscheme who originally made this for vscode. I just ported the theme to vim using one of @ sainnhe's colorscheme as a base
