### ISSUE TITLE
Weird background 

### ISSUE THREAD

**Issue by pavelshtanko** [ghifarit53/tokyonight-vim#19]
I have these backgrounds for various types of variables or function calls. 

<img width="572" alt="image" src="https://user-images.githubusercontent.com/24318220/103088116-190edb80-45ea-11eb-9b1e-f481c874e109.png">

How can I fix it? 

p.s. The theme is amazing!

**Comment by ghifarit53** [comment]
That's odd. Could you post your `.vimrc` or `init.vim` so I can reproduce it?

And thanks for the compliment! all credits goes to @ enkia (the original author of the colorscheme)

**Comment by pavelshtanko** [comment]
https://gist.github.com/pavelshtanko/fe2d37f72d91f7923b074cfab717a362

a bit messy but that's it

**Comment by ghifarit53** [comment]
What's the terminal emulator you're currently using and would you mind trying other terminal to see if the problem persist?

**Comment by pavelshtanko** [comment]
iterm2, I'll try alacritty now

**Comment by pavelshtanko** [comment]
same in alacritty

**Comment by ghifarit53** [comment]
Seems like the problem lies in the `.vimrc`

**Comment by ghifarit53** [comment]
Sorry, I can't seem to reproduce the issue
![image](https://user-images.githubusercontent.com/59758342/103090858-ea622680-4624-11eb-81e1-2864fc01e60b.png)
Just my guess, but maybe you happen to have other .vim files that override settings in vimrc (maybe in autoload or after folder in ~/.vim). Also did the issue happen just recently?

**Comment by jonboy-ai** [comment]
Same issue here. Any solution @pavelshtanko ?

**Comment by benjamingarcia** [comment]
Hello, I have the same issue: Theme works on macvim, but not on vim or neovim in a terminal (I tested with alacritty, iterm2 and terminal)

**Comment by benjamingarcia** [comment]
Hello! 
Well, I found how fix this issues thanks to another theme (https://github.com/joshdick/onedark.vim). 
It's an issues with italic encoding I suppose. 
I follow [this solution](https://github.com/joshdick/onedark.vim/issues/97#issuecomment-299719352), and now it's fixed.
And before this I update tmux.conf thanks to [this articles](https://rsapkf.xyz/blog/enabling-italics-vim-tmux)
on alacritty, I set Term as `TERM: xterm-256color`

and finally, on vim : 
```
set termguicolors
set t_Co=256
```

@Hamptonjc @pavelshtanko

**Comment by pavelshtanko** [comment]
@benjamingarcia nope... sorry, didn't solve the problem or me

**Comment by pavelshtanko** [comment]
> Hello!
> Well, I found how fix this issues thanks to another theme (https://github.com/joshdick/onedark.vim).
> It's an issues with italic encoding I suppose.
> I follow [this solution](https://github.com/joshdick/onedark.vim/issues/97#issuecomment-299719352), and now it's fixed.
> And before this I update tmux.conf thanks to [this articles](https://rsapkf.xyz/blog/enabling-italics-vim-tmux)
> on alacritty, I set Term as `TERM: xterm-256color`
> 
> and finally, on vim :
> 
> ```
> set termguicolors
> set t_Co=256
> ```
> 
> @Hamptonjc @pavelshtanko

It works! Indeed at first I didn't follow the link with solution, but now it's totally fine. 

Thanks for your helP!
