### ISSUE TITLE
Feature Request: add an airline theme?

### ISSUE THREAD

**Issue by bgianfo** [ghifarit53/tokyonight-vim#2]
Love the theme, only thing I would like is for an airline theme to be available as well. 
https://github.com/vim-airline/vim-airline-themes

**Comment by ghifarit53** [comment]
Thanks for the pull, sorry for making you waiting, i've been busy these few days. Will merge it and close this after trying it myself

**Comment by ghifarit53** [comment]
done! check the latest push
