### ISSUE TITLE
Not working correctly

### ISSUE THREAD

**Issue by RossComputerGuy** [ghifarit53/tokyonight-vim#4]
![screenshot](https://user-images.githubusercontent.com/19699320/95672156-0c075200-0b8e-11eb-8912-1c28af3e2300.png)
As you can see, its not looking right in Vim. Terminal is URxvt.

**Comment by RossComputerGuy** [comment]
Removing `set termguicolors` fixed it.

**Comment by ghifarit53** [comment]
@RossComputerGuy that's strange, you actually need to add `set termguicolors` to make the colorscheme working correctly. I tested it after seeing this issue. Without `termguicolors` being set, you're actually revert to 256 color version of this theme

with `set termguicolors`
![scr-2020-10-11_17 09 22](https://user-images.githubusercontent.com/59758342/95675930-48e14200-0baa-11eb-903e-878a63f0de1c.png)

without `set termguicolors`
![scr-2020-10-11_17 09 48](https://user-images.githubusercontent.com/59758342/95675947-657d7a00-0baa-11eb-8046-1167bf4b943c.png)

just my guess, but maybe it has something to do with your `$TERM` variable

**Comment by stoicAlchemist** [comment]
I just got the same issue, apparently it has to do with ordering, if you `set termguicolors` after the colorscheme has been set, you'll get no colors applied to your nvim (maybe reset?), if you do it before setting the colorscheme, you're gonna get them fine.
